# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('state', models.TextField(choices=[('open', 'open'), ('closed', 'open')], default=('open', 'open'), verbose_name='state')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('liked_by', models.ManyToManyField(related_name='liked_suggestions', through='beat_box.Like', to=settings.AUTH_USER_MODEL, verbose_name='likes')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat_box.Suggestion'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('author', 'suggestion')]),
        ),
    ]
